-- Generated by Matugen from Nyvorel's native Lua color template.
hl.config({["general"] = { ["col"] = {
    ["active_border"] = "rgba({{colors.primary.default.hex_stripped}}AA)",
    ["inactive_border"] = "rgba({{colors.outline_variant.default.hex_stripped}}88)",
}}})
hl.config({["misc"] = {
    ["background_color"] = "rgba({{colors.background.default.hex_stripped}}FF)",
}})
