# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

# Optional X11 Num Lock helper; add "exec-once = numlockx on" here if installed.
